In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/Salaries.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/Salaries.csv'

In [4]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [7]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.shape

(78, 6)

In [10]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [11]:
df.isnull

<bound method DataFrame.isnull of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [13]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [14]:
df.describe

<bound method NDFrame.describe of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [15]:
df['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [16]:
df['salary'].mean()

108023.78205128205

In [17]:
df['salary'].median()

104671.0

In [18]:
df['salary'].mode()

0    92000
Name: salary, dtype: int64

In [20]:
df['salary'].var()

800531254.0427904

In [21]:
df['salary'].std()

28293.661022264165

In [23]:
df['salary'].skew()

0.45210256755588096

In [24]:
df[['salary','phd']].mean()

salary    108023.782051
phd           19.705128
dtype: float64

In [25]:
df[['salary','phd']].median()

salary    104671.0
phd           18.5
dtype: float64

In [26]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [27]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [28]:
df['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [29]:
df['salary'].mean()

108023.78205128205

In [30]:
df['salary'].median()

104671.0

In [31]:
df['salary'].mode()

0    92000
Name: salary, dtype: int64

In [32]:
df['salary'].var()

800531254.0427904

In [33]:
df['salary'].std()

28293.661022264165

In [34]:
df['salary'].skew()

0.45210256755588096

In [35]:
df[['salary','phd']].mean()

salary    108023.782051
phd           19.705128
dtype: float64

In [36]:
df[['salary','phd']].median()

salary    104671.0
phd           18.5
dtype: float64

In [37]:
df.mean(numeric_only=True)

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [38]:
df.median(numeric_only=True)

phd            18.5
service        14.5
salary     104671.0
dtype: float64

In [40]:
# prompt: filter the record where the salary is greater than 500000 in df

df_filtered = df[df['salary'] > 500000]
df_filtered

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [43]:
df[df['salary'] >50000]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [44]:
df.iloc[:,:]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [45]:
df.iloc[0:10,0:3]

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [46]:
df.iloc[0:10,1:5]

  discipline  phd  service   sex
0          B   56       49  Male
1          A   12        6  Male
2          A   23       20  Male
3          A   40       31  Male
4          B   20       18  Male
5          A   20       20  Male
6          A   20       17  Male
7          A   18       18  Male
8          A   29       19  Male
9          A   51       51  Male

In [47]:
df.iloc[0:10,[1,3,5]]

  discipline  service  salary
0          B       49  186960
1          A        6   93000
2          A       20  110515
3          A       31  131205
4          B       18  104800
5          A       20  122400
6          A       17   81285
7          A       18  126300
8          A       19   94350
9          A       51   57800

In [48]:
# prompt: i want to select 10 rows and columns  1,3,5

df.iloc[0:10, [1, 3, 5]]

  discipline  service  salary
0          B       49  186960
1          A        6   93000
2          A       20  110515
3          A       31  131205
4          B       18  104800
5          A       20  122400
6          A       17   81285
7          A       18  126300
8          A       19   94350
9          A       51   57800

In [3]:
df.loc[0, 'salary']

NameError: name 'df' is not defined